apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pjknvl5wv-nodejs 
  janus-idp.io/tekton: pjknvl5wv-nodejs
  backstage.io/kubernetes-id: pjknvl5wv-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pjknvl5wv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml