apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pjknvl5wv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pjknvl5wv-nodejs 
  name: pjknvl5wv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pjknvl5wv-nodejs 
